services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/app/postgres:/var/lib/postgresql/data
  api:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env